// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ckagvfryqclitidrjoky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrYWd2ZnJ5cWNsaXRpZHJqb2t5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NTQzNTcsImV4cCI6MjA2ODIzMDM1N30.lq-c8ndrJM6h-0AQ6tZ3jcsLuaarWRiSg14d32TARDU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});